
import type { Agent, Content, Draft, Platform, CommunityMetrics, ActivityLog } from '@/types';

// Mock data for development and testing when Supabase is not configured

export const mockPlatforms: Platform[] = [
  {
    id: '1',
    name: 'Instagram',
    type: 'instagram',
    isConnected: true,
    accountHandle: '@blkout_uk',
    accountUrl: 'https://instagram.com/blkout_uk',
    lastSync: new Date('2025-11-16T10:30:00'),
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    id: '2',
    name: 'LinkedIn',
    type: 'linkedin',
    isConnected: true,
    accountHandle: 'BLKOUT UK',
    accountUrl: 'https://linkedin.com/company/blkout-uk',
    lastSync: new Date('2025-11-16T09:15:00'),
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    id: '3',
    name: 'Twitter',
    type: 'twitter',
    isConnected: false,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
];

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'Griot',
    type: 'griot',
    status: 'active',
    description: 'Storytelling and content creation rooted in Black feminist thought',
    capabilities: ['Content Creation', 'Storytelling', 'Cultural Context', 'Voice & Tone'],
    lastActive: new Date('2025-11-16T14:30:00'),
    totalContentGenerated: 127,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    id: '2',
    name: 'Listener',
    type: 'listener',
    status: 'active',
    description: 'Social monitoring and community intelligence gathering',
    capabilities: ['Social Listening', 'Trend Analysis', 'Sentiment Analysis', 'Intelligence Gathering'],
    lastActive: new Date('2025-11-16T14:45:00'),
    totalContentGenerated: 0,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    id: '3',
    name: 'Weaver',
    type: 'weaver',
    status: 'active',
    description: 'Community engagement and relationship building',
    capabilities: ['Community Engagement', 'Relationship Building', 'Conversation Facilitation', 'Trust Development'],
    lastActive: new Date('2025-11-16T13:20:00'),
    totalContentGenerated: 89,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    id: '4',
    name: 'Strategist',
    type: 'strategist',
    status: 'paused',
    description: 'Campaign planning and strategic content coordination',
    capabilities: ['Campaign Planning', 'Strategic Analysis', 'Content Coordination', 'Timeline Management'],
    lastActive: new Date('2025-11-15T16:00:00'),
    totalContentGenerated: 34,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-15'),
  },
  {
    id: '5',
    name: 'Herald',
    type: 'herald',
    status: 'active',
    description: 'Community communications and newsletter curation',
    capabilities: ['Newsletter Curation', 'Weekly Updates', 'Monthly Digests', 'Community Highlights', 'SendFox Integration'],
    lastActive: new Date('2025-11-16T15:00:00'),
    totalContentGenerated: 12,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
];

export const mockContent: Content[] = [
  {
    id: '1',
    title: 'Community Spotlight: Local Organizers',
    body: 'Today we celebrate the incredible work of community organizers who move at the speed of trust...',
    contentType: 'post',
    status: 'published',
    platforms: ['instagram', 'linkedin'],
    publishedAt: new Date('2025-11-15T10:00:00'),
    agentId: '1',
    agentType: 'griot',
    hashtags: ['#CommunityPower', '#BlackFeminism', '#OrganizeWithPurpose'],
    engagementMetrics: {
      likes: 342,
      comments: 67,
      shares: 89,
      conversationDepth: 8.5,
      relationshipScore: 92,
    },
    createdAt: new Date('2025-11-14'),
    updatedAt: new Date('2025-11-15'),
  },
  {
    id: '2',
    title: 'Upcoming Workshop: Radical Care Practices',
    body: 'Join us next week for a deep dive into radical care practices in organizing...',
    contentType: 'post',
    status: 'scheduled',
    platforms: ['instagram', 'facebook'],
    scheduledFor: new Date('2025-11-18T14:00:00'),
    agentId: '1',
    agentType: 'griot',
    hashtags: ['#RadicalCare', '#CommunityWellness'],
    createdAt: new Date('2025-11-16'),
    updatedAt: new Date('2025-11-16'),
  },
];

export const mockDrafts: Draft[] = [
  {
    id: '1',
    title: 'Black Feminist Thought in Action',
    body: 'Exploring how Black feminist frameworks shape our organizing work and community building...',
    contentType: 'article',
    platforms: ['linkedin'],
    agentId: '1',
    agentType: 'griot',
    status: 'pending_review',
    hashtags: ['#BlackFeminism', '#OrganizingWork'],
    createdAt: new Date('2025-11-16T08:00:00'),
    updatedAt: new Date('2025-11-16T08:00:00'),
  },
  {
    id: '2',
    title: 'Community Response: Climate Justice',
    body: 'Our community\'s perspective on the intersection of racial justice and climate action...',
    contentType: 'thread',
    platforms: ['twitter', 'instagram'],
    agentId: '3',
    agentType: 'weaver',
    status: 'approved',
    hashtags: ['#ClimateJustice', '#RacialJustice'],
    createdAt: new Date('2025-11-16T09:30:00'),
    updatedAt: new Date('2025-11-16T10:00:00'),
  },
];

export const mockCommunityMetrics: CommunityMetrics = {
  totalMembers: 2847,
  activeMembers: 1234,
  newMembers: 156,
  engagementQuality: 87,
  conversationDepth: 7.8,
  trustScore: 91,
  contentResonance: 84,
  period: 'week',
  date: new Date('2025-11-16'),
};

export const mockActivityLogs: ActivityLog[] = [
  {
    id: '1',
    agentId: '1',
    agentType: 'griot',
    action: 'content_created',
    description: 'Generated draft: "Black Feminist Thought in Action"',
    timestamp: new Date('2025-11-16T08:00:00'),
  },
  {
    id: '2',
    agentId: '2',
    agentType: 'listener',
    action: 'intelligence_gathered',
    description: 'Identified trending topic: Climate Justice',
    timestamp: new Date('2025-11-16T09:00:00'),
  },
  {
    id: '3',
    agentId: '3',
    agentType: 'weaver',
    action: 'engagement_response',
    description: 'Responded to 23 community comments',
    timestamp: new Date('2025-11-16T13:20:00'),
  },
];
