# comms-blkout Dockerfile for Coolify
# Serves both static frontend AND API routes via Express
FROM node:20-alpine AS builder

WORKDIR /app

# Cache bust - forces full rebuild when changed (fixes corrupted cached layers)
LABEL build.date="2026-02-03"

# Copy package files
COPY package*.json ./

# Install all dependencies (including dev for build)
RUN npm ci

# Copy source
COPY . .

# Build args for Vite (import.meta.env is replaced at build time)
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_AUTH_DISABLED=true
ARG VITE_MOCK_USER_EMAIL=admin@blkout.dev
ARG VITE_MOCK_USER_NAME=BLKOUT Admin
ARG VITE_GEMINI_API
ARG VITE_INSTAGRAM_CLIENT_ID
ARG VITE_INSTAGRAM_CLIENT_SECRET
ARG VITE_INSTAGRAM_REDIRECT_URI
ARG VITE_TIKTOK_CLIENT_KEY
ARG VITE_TIKTOK_CLIENT_SECRET
ARG VITE_LINKEDIN_CLIENT_ID
ARG VITE_LINKEDIN_CLIENT_SECRET
ARG VITE_YOUTUBE_CLIENT_ID
ARG VITE_YOUTUBE_CLIENT_SECRET
ARG VITE_TWITTER_CLIENT_ID
ARG VITE_TWITTER_CLIENT_SECRET
ARG VITE_CANVA_CLIENT_ID
ARG VITE_CANVA_CLIENT_SECRET
ARG VITE_CANVA_REDIRECT_URI
ARG VITE_HEARTBEAT_API_KEY
ARG VITE_HEARTBEAT_NEWS_CHANNEL_ID

# Make args available as env vars during build
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_AUTH_DISABLED=$VITE_AUTH_DISABLED
ENV VITE_MOCK_USER_EMAIL=$VITE_MOCK_USER_EMAIL
ENV VITE_MOCK_USER_NAME=$VITE_MOCK_USER_NAME
ENV VITE_GEMINI_API=$VITE_GEMINI_API
ENV VITE_INSTAGRAM_CLIENT_ID=$VITE_INSTAGRAM_CLIENT_ID
ENV VITE_INSTAGRAM_CLIENT_SECRET=$VITE_INSTAGRAM_CLIENT_SECRET
ENV VITE_INSTAGRAM_REDIRECT_URI=$VITE_INSTAGRAM_REDIRECT_URI
ENV VITE_TIKTOK_CLIENT_KEY=$VITE_TIKTOK_CLIENT_KEY
ENV VITE_TIKTOK_CLIENT_SECRET=$VITE_TIKTOK_CLIENT_SECRET
ENV VITE_LINKEDIN_CLIENT_ID=$VITE_LINKEDIN_CLIENT_ID
ENV VITE_LINKEDIN_CLIENT_SECRET=$VITE_LINKEDIN_CLIENT_SECRET
ENV VITE_YOUTUBE_CLIENT_ID=$VITE_YOUTUBE_CLIENT_ID
ENV VITE_YOUTUBE_CLIENT_SECRET=$VITE_YOUTUBE_CLIENT_SECRET
ENV VITE_TWITTER_CLIENT_ID=$VITE_TWITTER_CLIENT_ID
ENV VITE_TWITTER_CLIENT_SECRET=$VITE_TWITTER_CLIENT_SECRET
ENV VITE_CANVA_CLIENT_ID=$VITE_CANVA_CLIENT_ID
ENV VITE_CANVA_CLIENT_SECRET=$VITE_CANVA_CLIENT_SECRET
ENV VITE_CANVA_REDIRECT_URI=$VITE_CANVA_REDIRECT_URI
ENV VITE_HEARTBEAT_API_KEY=$VITE_HEARTBEAT_API_KEY
ENV VITE_HEARTBEAT_NEWS_CHANNEL_ID=$VITE_HEARTBEAT_NEWS_CHANNEL_ID

# Build frontend (Vite) and server (Express + API)
RUN npm run build

# Production stage
FROM node:20-alpine AS runner

WORKDIR /app

# Copy built assets
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/server-dist ./server-dist
COPY --from=builder /app/package*.json ./

# Install production dependencies only
RUN npm install --omit=dev

# Expose port
EXPOSE 3000

# Run the Express server (serves static + API)
CMD ["node", "server-dist/server.js"]
