/**
 * ValuesCheck Component
 *
 * Enforces BLKOUT's values-led, truth-based content standards before publishing.
 * Ensures content is factually accurate, demographically authentic, and maintains
 * recognizable BLKOUT brand voice/visual identity.
 *
 * Philosophy: "AI is creative assistant, not publisher" - human verification required.
 */

import { useState } from 'react';
import { AlertTriangle, Check, X } from 'lucide-react';

export interface ValidationCheck {
  id: string;
  category: 'data' | 'representation' | 'values' | 'branding' | 'design_voice';
  question: string;
  required: boolean;
  status: 'pending' | 'pass' | 'fail';
  helpText?: string;
}

export interface ValidationResult {
  checkId: string;
  passed: boolean;
  timestamp: Date;
  notes?: string;
}

interface ValuesCheckProps {
  contentType: 'image' | 'video' | 'text' | 'campaign';
  onValidationComplete: (passed: boolean, results: ValidationResult[]) => void;
  onCancel?: () => void;
}

/**
 * Base validation checklist - applies to all content types
 * Additional checks can be added based on contentType
 */
const BASE_VALIDATION_CHECKLIST: ValidationCheck[] = [
  {
    id: 'data_verified',
    category: 'data',
    question: 'All statistics and numbers verified from real sources?',
    required: true,
    status: 'pending',
    helpText: 'Check Supabase database, Google Analytics, or other verified sources. No fabricated data.'
  },
  {
    id: 'demographics_authentic',
    category: 'representation',
    question: 'All people shown authentically represent target community (Black queer men)?',
    required: true,
    status: 'pending',
    helpText: 'BLKOUT is for and by Black queer men. Ensure demographic accuracy in all visuals.'
  },
  {
    id: 'no_fabrication',
    category: 'values',
    question: 'No fabricated data, fake testimonials, or misleading claims?',
    required: true,
    status: 'pending',
    helpText: 'Values-led means truth-based. Every claim must be verifiable.'
  },
  {
    id: 'official_branding',
    category: 'branding',
    question: 'Official BLKOUT logos used (not AI-generated text)?',
    required: true,
    status: 'pending',
    helpText: 'Use assets from /assets/brand/ - LOGOBLKOUT0725.png or blkout_logo_roundel_colour.png'
  },
  {
    id: 'app_descriptions_correct',
    category: 'values',
    question: 'App descriptions factually accurate? (Critical Frequency = mental health, Down = hook-up)',
    required: true,
    status: 'pending',
    helpText: 'Critical Frequency: population health mental wellbeing. Down: hook-up app for Black queer men.'
  },
  {
    id: 'brand_voice_recognizable',
    category: 'design_voice',
    question: 'Content is recognizably BLKOUT at a glance? (colors, typography, style)',
    required: true,
    status: 'pending',
    helpText: 'Purple (#a855f7), Gold (#f59e0b), Green (#10b981), Teal (#14b8a6). IVOR voice: sophisticated wit meets Black British warmth.'
  },
  {
    id: 'visual_consistency',
    category: 'design_voice',
    question: 'Visual design matches BLKOUT brand guidelines? (regardless of AI provider)',
    required: true,
    status: 'pending',
    helpText: 'Consistent aesthetic whether generated by Gemini, Wan Video, or other providers. Brand voice > provider.'
  },
  {
    id: 'cta_clear',
    category: 'branding',
    question: 'Clear call-to-action with URL present?',
    required: false,
    status: 'pending',
    helpText: 'Format: [Action Verb] + [Destination]. Examples: "Learn more: BLKOUTUK.COM", "Subscribe: BLKOUTUK.COM/newsletter"'
  }
];

export function ValuesCheck({ onValidationComplete, onCancel }: ValuesCheckProps) {
  const [checks, setChecks] = useState<ValidationCheck[]>(BASE_VALIDATION_CHECKLIST);
  const [notes, setNotes] = useState<Record<string, string>>({});

  const handleCheckChange = (checkId: string, passed: boolean) => {
    setChecks(prev => prev.map(check =>
      check.id === checkId
        ? { ...check, status: passed ? 'pass' : 'fail' }
        : check
    ));
  };

  const handleComplete = () => {
    // Verify all required checks passed
    const requiredChecks = checks.filter(c => c.required);
    const allRequiredPassed = requiredChecks.every(c => c.status === 'pass');

    // Create results
    const results: ValidationResult[] = checks.map(check => ({
      checkId: check.id,
      passed: check.status === 'pass',
      timestamp: new Date(),
      notes: notes[check.id]
    }));

    onValidationComplete(allRequiredPassed, results);
  };

  const allRequiredChecksPassed = checks
    .filter(c => c.required)
    .every(c => c.status === 'pass');

  const requiredCount = checks.filter(c => c.required).length;
  const passedCount = checks.filter(c => c.required && c.status === 'pass').length;

  return (
    <div className="bg-amber-50 border-2 border-amber-300 rounded-xl p-6 max-w-2xl">
      {/* Header */}
      <div className="flex items-start gap-4 mb-6">
        <div className="flex-shrink-0 p-3 bg-amber-100 rounded-lg">
          <AlertTriangle className="text-amber-700" size={28} />
        </div>
        <div className="flex-1">
          <h3 className="font-bold text-gray-900 text-lg mb-1">
            Values-Led Review Required
          </h3>
          <p className="text-sm text-gray-700">
            BLKOUT is values-led and truth-based. Verify each item before publishing.
            Content must be recognizably BLKOUT regardless of generation provider.
          </p>
          <div className="mt-2 flex items-center gap-2 text-xs text-gray-600">
            <span className="font-medium">Progress:</span>
            <span>{passedCount} of {requiredCount} required checks passed</span>
          </div>
        </div>
      </div>

      {/* Checklist */}
      <div className="space-y-4 mb-6">
        {checks.map((check) => (
          <div
            key={check.id}
            className={`p-4 rounded-lg border-2 transition-all ${
              check.status === 'pass'
                ? 'bg-green-50 border-green-300'
                : check.status === 'fail'
                ? 'bg-red-50 border-red-300'
                : 'bg-white border-gray-200'
            }`}
          >
            <div className="flex items-start gap-3 mb-2">
              <div className="flex gap-2 pt-1">
                <button
                  onClick={() => handleCheckChange(check.id, true)}
                  className={`p-1.5 rounded transition-colors ${
                    check.status === 'pass'
                      ? 'bg-green-600 text-white'
                      : 'bg-gray-200 text-gray-600 hover:bg-green-100'
                  }`}
                  aria-label={`Mark "${check.question}" as passed`}
                >
                  <Check size={16} />
                </button>
                <button
                  onClick={() => handleCheckChange(check.id, false)}
                  className={`p-1.5 rounded transition-colors ${
                    check.status === 'fail'
                      ? 'bg-red-600 text-white'
                      : 'bg-gray-200 text-gray-600 hover:bg-red-100'
                  }`}
                  aria-label={`Mark "${check.question}" as failed`}
                >
                  <X size={16} />
                </button>
              </div>

              <div className="flex-1">
                <div className="flex items-center gap-2 mb-1">
                  <span className={`px-2 py-0.5 text-[10px] font-bold uppercase rounded ${
                    check.category === 'data' ? 'bg-blue-200 text-blue-800' :
                    check.category === 'representation' ? 'bg-purple-200 text-purple-800' :
                    check.category === 'values' ? 'bg-red-200 text-red-800' :
                    check.category === 'design_voice' ? 'bg-indigo-200 text-indigo-800' :
                    'bg-gray-200 text-gray-800'
                  }`}>
                    {check.category.replace('_', ' ')}
                  </span>
                  {check.required && (
                    <span className="text-red-600 font-bold text-sm">*</span>
                  )}
                </div>

                <p className="text-sm font-medium text-gray-900 mb-1">
                  {check.question}
                </p>

                {check.helpText && (
                  <p className="text-xs text-gray-600 italic">
                    {check.helpText}
                  </p>
                )}

                {/* Optional notes field */}
                <input
                  type="text"
                  value={notes[check.id] || ''}
                  onChange={(e) => setNotes(prev => ({ ...prev, [check.id]: e.target.value }))}
                  placeholder="Optional notes (data source, verification method, etc.)"
                  className="mt-2 w-full px-3 py-1.5 text-xs border border-gray-300 rounded focus:outline-none focus:border-gray-400 bg-white"
                />
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Warning if required checks not passed */}
      {!allRequiredChecksPassed && (
        <div className="mb-4 p-3 bg-amber-100 border border-amber-300 rounded-lg">
          <p className="text-sm text-amber-900 font-medium">
            ⚠️ All required checks must pass before approval
          </p>
        </div>
      )}

      {/* Actions */}
      <div className="flex gap-3">
        {onCancel && (
          <button
            onClick={onCancel}
            className="flex-1 py-3 px-4 bg-gray-200 hover:bg-gray-300 text-gray-800 rounded-lg font-medium transition-colors"
          >
            Cancel
          </button>
        )}
        <button
          onClick={handleComplete}
          disabled={!allRequiredChecksPassed}
          className="flex-1 py-3 px-4 bg-green-600 hover:bg-green-700 text-white rounded-lg font-medium transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed"
        >
          {allRequiredChecksPassed ? 'Confirm Values Check Complete' : 'Complete All Required Checks'}
        </button>
      </div>

      {/* Footer */}
      <div className="mt-4 pt-4 border-t border-amber-200">
        <p className="text-xs text-gray-600 italic">
          "AI is creative assistant, not publisher" - Every published item requires human verification.
        </p>
      </div>
    </div>
  );
}
