/**
 * Editorial Handlers
 * Handle editorial prompt and reply workflows
 */
import { supabase, RESEND_API_KEY, EDITOR_EMAIL, EDITOR_NAME, EDITOR_AVATAR_URL, OPENROUTER_API_KEY } from '../config.js';
import { generateHTMLWithEditor } from '../generators/html.js';
/**
 * Send editorial prompt email
 */
export async function handleSendEditorialPrompt(req, res) {
    const { edition_id } = req.body;
    if (!edition_id) {
        return res.status(400).json({ error: 'Missing edition_id' });
    }
    const { data: edition, error } = await supabase
        .from('newsletter_editions')
        .select('id, title, edition_type, content_sections')
        .eq('id', edition_id)
        .single();
    if (error || !edition) {
        return res.status(404).json({ error: 'Edition not found' });
    }
    const contentSections = edition.content_sections;
    const highlights = contentSections?.highlights?.slice(0, 3).map(h => `• ${h.title}`).join('\n') || 'No highlights';
    const events = contentSections?.events?.slice(0, 3).map(e => `• ${e.title} (${e.date})`).join('\n') || 'No events';
    const emailHtml = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #1a1a2e;">📝 Editorial Prompt for ${edition.title}</h2>

      <p>Hi ${EDITOR_NAME},</p>

      <p>The Herald agent has prepared a new <strong>${edition.edition_type}</strong> newsletter and needs your "From the Editor" section.</p>

      <div style="background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 20px 0;">
        <h3 style="margin-top: 0;">This Week's Content:</h3>
        <p><strong>Highlights:</strong></p>
        <pre style="white-space: pre-wrap; font-family: inherit;">${highlights}</pre>
        <p><strong>Upcoming Events:</strong></p>
        <pre style="white-space: pre-wrap; font-family: inherit;">${events}</pre>
      </div>

      <p><strong>Please reply with:</strong></p>
      <ol>
        <li><strong>Topic:</strong> What's on your mind this week? (1-2 sentences)</li>
        <li><strong>Key Takeaway:</strong> What should readers feel/do after reading? (1 sentence)</li>
      </ol>

      <p style="color: #666; font-size: 14px;">
        Simply reply to this email. The Herald agent will transform your response into a polished ~100 word "From the Editor" section.
      </p>

      <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
      <p style="color: #999; font-size: 12px;">
        Edition ID: ${edition_id}<br>
        Auto-generated by Herald Newsletter Agent
      </p>
    </div>
  `;
    if (RESEND_API_KEY) {
        try {
            const response = await fetch('https://api.resend.com/emails', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${RESEND_API_KEY}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    from: 'BLKOUT Herald <noreply@blkoutuk.com>',
                    to: EDITOR_EMAIL,
                    subject: `📝 Editorial needed: ${edition.title}`,
                    html: emailHtml,
                    reply_to: EDITOR_EMAIL
                })
            });
            if (!response.ok) {
                const errorText = await response.text();
                console.error('[Herald] Resend error:', errorText);
                return res.status(500).json({ error: 'Failed to send email', details: errorText });
            }
            await supabase
                .from('newsletter_editions')
                .update({
                editor_prompt_sent_at: new Date().toISOString(),
                editor_name: EDITOR_NAME,
                editor_avatar_url: EDITOR_AVATAR_URL
            })
                .eq('id', edition_id);
            return res.status(200).json({
                success: true,
                message: `Editorial prompt sent to ${EDITOR_EMAIL}`,
                edition_id
            });
        }
        catch (err) {
            console.error('[Herald] Email error:', err);
            return res.status(500).json({ error: 'Failed to send email' });
        }
    }
    return res.status(200).json({
        success: true,
        message: 'Email service not configured. Use manual prompt below.',
        manual_prompt: {
            to: EDITOR_EMAIL,
            subject: `📝 Editorial needed: ${edition.title}`,
            body: `Topic: What's on your mind this week?\nKey Takeaway: What should readers feel/do?\n\nContent summary:\n${highlights}\n\n${events}`
        },
        edition_id
    });
}
/**
 * Process editorial reply and generate From the Editor section
 */
export async function handleEditorialReply(req, res) {
    const { edition_id, topic, key_takeaway } = req.body;
    if (!edition_id || !topic) {
        return res.status(400).json({ error: 'Missing edition_id or topic' });
    }
    const prompt = `Write a warm, personal "From the Editor" section for BLKOUT UK's newsletter (~100 words).

Editor's input:
- Topic: ${topic}
- Key takeaway: ${key_takeaway || 'Connect with community'}

Guidelines:
- Write in first person as ${EDITOR_NAME}, the editor
- Be warm, authentic, and community-focused
- Reference Black LGBTQ+ joy and connection
- End with an encouraging message
- Keep it to approximately 100 words
- Do NOT include a greeting like "Dear readers" - start with the content
- Do NOT include a sign-off - that will be added separately

Write ONLY the paragraph text, nothing else.`;
    let editorNote = '';
    if (OPENROUTER_API_KEY) {
        try {
            const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
                    'Content-Type': 'application/json',
                    'HTTP-Referer': 'https://comms-blkout.vercel.app',
                    'X-Title': 'BLKOUT Herald Newsletter'
                },
                body: JSON.stringify({
                    model: 'anthropic/claude-3.5-haiku',
                    messages: [{ role: 'user', content: prompt }],
                    max_tokens: 300,
                    temperature: 0.7
                })
            });
            if (response.ok) {
                const data = await response.json();
                editorNote = data.choices?.[0]?.message?.content?.trim() || '';
            }
        }
        catch (err) {
            console.error('[Herald] AI generation error:', err);
        }
    }
    if (!editorNote) {
        editorNote = `${topic} ${key_takeaway || 'I hope you find something in this edition that speaks to you.'}`;
    }
    const { error: updateError } = await supabase
        .from('newsletter_editions')
        .update({
        editor_note: editorNote,
        editor_prompt_topic: `${topic} | ${key_takeaway || ''}`,
        editor_prompt_responded: true,
        updated_at: new Date().toISOString()
    })
        .eq('id', edition_id);
    if (updateError) {
        return res.status(500).json({ error: 'Failed to save editor note', details: updateError.message });
    }
    const { data: edition } = await supabase
        .from('newsletter_editions')
        .select('*')
        .eq('id', edition_id)
        .single();
    if (edition) {
        const contentSections = edition.content_sections;
        const sections = [
            { type: 'highlights', title: 'Community Highlights', items: contentSections?.highlights || [] },
            { type: 'events', title: 'Upcoming Events', items: contentSections?.events || [] },
            { type: 'resources', title: 'Community Resources', items: contentSections?.resources || [] }
        ];
        const htmlContent = generateHTMLWithEditor(edition.title, contentSections?.intro || '', sections, edition.edition_type, editorNote, EDITOR_NAME, EDITOR_AVATAR_URL);
        await supabase
            .from('newsletter_editions')
            .update({ html_content: htmlContent })
            .eq('id', edition_id);
    }
    return res.status(200).json({
        success: true,
        editor_note: editorNote,
        edition_id
    });
}
